/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as BestPreschoolInRatlamRouteImport } from './routes/best-preschool-in-ratlam'
import { Route as BookTourRouteImport } from './routes/book-tour'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GalleryRouteImport } from './routes/gallery'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const BestPreschoolInRatlamRoute = BestPreschoolInRatlamRouteImport.update({
  id: '/best-preschool-in-ratlam',
  path: '/best-preschool-in-ratlam',
  getParentRoute: () => rootRouteImport,
} as any)
const BookTourRoute = BookTourRouteImport.update({
  id: '/book-tour',
  path: '/book-tour',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admissions': typeof AdmissionsRoute
  '/best-preschool-in-ratlam': typeof BestPreschoolInRatlamRoute
  '/book-tour': typeof BookTourRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admissions': typeof AdmissionsRoute
  '/best-preschool-in-ratlam': typeof BestPreschoolInRatlamRoute
  '/book-tour': typeof BookTourRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admissions': typeof AdmissionsRoute
  '/best-preschool-in-ratlam': typeof BestPreschoolInRatlamRoute
  '/book-tour': typeof BookTourRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admissions'
    | '/best-preschool-in-ratlam'
    | '/book-tour'
    | '/contact'
    | '/gallery'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admissions'
    | '/best-preschool-in-ratlam'
    | '/book-tour'
    | '/contact'
    | '/gallery'
  id:
    | '__root__'
    | '/'
    | '/admissions'
    | '/best-preschool-in-ratlam'
    | '/book-tour'
    | '/contact'
    | '/gallery'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdmissionsRoute: typeof AdmissionsRoute
  BestPreschoolInRatlamRoute: typeof BestPreschoolInRatlamRoute
  BookTourRoute: typeof BookTourRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/best-preschool-in-ratlam': {
      id: '/best-preschool-in-ratlam'
      path: '/best-preschool-in-ratlam'
      fullPath: '/best-preschool-in-ratlam'
      preLoaderRoute: typeof BestPreschoolInRatlamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-tour': {
      id: '/book-tour'
      path: '/book-tour'
      fullPath: '/book-tour'
      preLoaderRoute: typeof BookTourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdmissionsRoute: AdmissionsRoute,
  BestPreschoolInRatlamRoute: BestPreschoolInRatlamRoute,
  BookTourRoute: BookTourRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
